export const DRUG_SYNONYMS = {
  dolo: 'paracetamol',
  crocin: 'paracetamol',
  calpol: 'paracetamol',
  pcm: 'paracetamol',
  metrogyl: 'metronidazole',
  azithral: 'azithromycin',
  augmentin: 'amoxicillin-clavulanate',
  amoxyclav: 'amoxicillin-clavulanate',
  amox: 'amoxicillin',
  ecosprin: 'aspirin',
  disprin: 'aspirin',
  combiflam: 'ibuprofen-paracetamol',
  glycomet: 'metformin',
  glucophage: 'metformin',
  pan: 'pantoprazole',
  zifi: 'cefixime',
  telma: 'telmisartan',
  amlong: 'amlodipine',
};

export const RXNORM_LOOKUP = {
  paracetamol: '161',
  acetaminophen: '161',
  ibuprofen: '5640',
  aspirin: '1191',
  diclofenac: '3355',
  metformin: '6809',
  insulin: '5856',
  azithromycin: '18631',
  amoxicillin: '723',
  'amoxicillin-clavulanate': '19711',
  cefixime: '25033',
  levofloxacin: '82122',
  warfarin: '11289',
  clopidogrel: '32968',
  atorvastatin: '83367',
  simvastatin: '36567',
  pantoprazole: '40790',
  omeprazole: '7646',
  alprazolam: '596',
  diazepam: '3322',
  lisinopril: '29046',
  telmisartan: '73494',
  amlodipine: '17767',
  metronidazole: '6922',
};

export const CANONICAL_DRUGS = [...new Set(Object.keys(RXNORM_LOOKUP))];

export const INTERACTIONS = [
  {
    pair: ['warfarin', 'aspirin'],
    severity: 'red',
    message: 'Warfarin + Aspirin can significantly increase bleeding risk.',
    advice: 'Avoid unless specifically prescribed together and monitored closely.',
    evidence: 'high',
  },
  {
    pair: ['warfarin', 'ibuprofen'],
    severity: 'red',
    message: 'Warfarin + Ibuprofen increases serious gastrointestinal bleeding risk.',
    advice: 'Use safer alternatives and consult a physician urgently.',
    evidence: 'high',
  },
  {
    pair: ['clopidogrel', 'omeprazole'],
    severity: 'yellow',
    message: 'Omeprazole may reduce Clopidogrel effectiveness in some patients.',
    advice: 'Discuss switching to pantoprazole or alternate GI protection.',
    evidence: 'moderate',
  },
  {
    pair: ['azithromycin', 'simvastatin'],
    severity: 'yellow',
    message: 'Azithromycin with Simvastatin may increase muscle toxicity risk.',
    advice: 'Monitor for severe muscle pain and dark urine; consult your doctor.',
    evidence: 'moderate',
  },
  {
    pair: ['diclofenac', 'lisinopril'],
    severity: 'yellow',
    message: 'NSAIDs like Diclofenac can reduce antihypertensive effect and affect kidneys.',
    advice: 'Use shortest duration and monitor blood pressure/renal function.',
    evidence: 'moderate',
  },
  {
    pair: ['ibuprofen', 'lisinopril'],
    severity: 'yellow',
    message: 'Ibuprofen may blunt BP control with Lisinopril and stress kidneys.',
    advice: 'Avoid prolonged co-use without clinician supervision.',
    evidence: 'moderate',
  },
  {
    pair: ['metformin', 'levofloxacin'],
    severity: 'yellow',
    message: 'Levofloxacin may alter blood glucose in diabetic patients on Metformin.',
    advice: 'Check glucose more frequently during antibiotic course.',
    evidence: 'moderate',
  },
  {
    pair: ['aspirin', 'ibuprofen'],
    severity: 'yellow',
    message: 'Ibuprofen can interfere with Aspirin antiplatelet effect and increase GI risk.',
    advice: 'Time doses carefully or use alternatives after clinician review.',
    evidence: 'moderate',
  },
];

export const ADR_MAP = {
  // Expanded common ADRs aligned to FDA/NIH drug monographs (MedlinePlus + MedWatch reporting)
  amoxicillin: ['rash', 'swelling', 'gastritis', 'nausea', 'vomiting', 'diarrhea'],
  'amoxicillin-clavulanate': ['rash', 'swelling', 'gastritis', 'nausea', 'vomiting', 'diarrhea'],
  azithromycin: ['gastritis', 'dizziness', 'nausea', 'vomiting', 'diarrhea', 'headache', 'palpitations'],
  cefixime: ['gastritis', 'rash', 'nausea', 'vomiting', 'diarrhea'],
  levofloxacin: ['dizziness', 'fatigue', 'nausea', 'diarrhea', 'headache'],
  metronidazole: ['gastritis', 'dizziness', 'nausea', 'vomiting', 'headache'],
  diclofenac: ['gastritis', 'swelling', 'dizziness', 'nausea'],
  ibuprofen: ['gastritis', 'rash', 'swelling', 'dizziness', 'nausea', 'vomiting', 'headache'],
  aspirin: ['gastritis', 'swelling', 'nausea', 'vomiting', 'rash', 'bleeding'],
  metformin: ['gastritis', 'fatigue', 'nausea', 'diarrhea', 'headache'],
  amlodipine: ['swelling', 'dizziness', 'fatigue', 'gastritis', 'nausea'],
  atorvastatin: ['fatigue', 'headache', 'gastritis', 'nausea', 'muscle_pain'],
  simvastatin: ['fatigue', 'headache', 'gastritis', 'nausea', 'muscle_pain'],
  warfarin: ['bleeding', 'rash', 'gastritis'],
  clopidogrel: ['bleeding', 'rash', 'gastritis', 'dizziness'],
  omeprazole: ['gastritis', 'nausea', 'vomiting', 'diarrhea', 'headache'],
  pantoprazole: ['gastritis', 'nausea', 'vomiting', 'diarrhea', 'headache'],
  lisinopril: ['cough', 'dizziness', 'fatigue'],
  telmisartan: ['dizziness', 'fatigue'],
  paracetamol: ['rash', 'swelling', 'nausea', 'headache'],
  acetaminophen: ['rash', 'swelling', 'nausea', 'headache'],
  alprazolam: ['dizziness', 'fatigue'],
  diazepam: ['dizziness', 'fatigue'],
};

export const ANTIBIOTICS = [
  'amoxicillin',
  'amoxicillin-clavulanate',
  'azithromycin',
  'cefixime',
  'levofloxacin',
  'metronidazole',
];

export const SYMPTOM_LABELS = {
  rash: 'Skin Rash / Itching',
  gastritis: 'Stomach Pain / Acidity',
  swelling: 'Swelling of Face/Lips',
  dizziness: 'Dizziness / Giddiness',
  cough: 'Dry Cough (Persistent)',
  fever_pers: 'Fever not reducing (3+ days)',
  recur_inf: 'Recurring Infection',
  fatigue: 'Extreme Weakness',
  nausea: 'Nausea',
  vomiting: 'Vomiting',
  diarrhea: 'Diarrhea',
  headache: 'Headache',
  bleeding: 'Unusual Bleeding / Bruising',
  palpitations: 'Fast or Irregular Heartbeat',
  muscle_pain: 'Muscle Pain / Weakness',
};
